config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/colstella2.5_lora128_bsz256x2_lr5e-4
  wandb_project: "Davit"
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColStella2_5_Processor
    pretrained_model_name_or_path:  "./models/colstella2.5_base" # "./models/paligemma-3b-mix-448"
    # num_image_tokens: 2048
    # max_length: 50

  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColStella2_5
    pretrained_model_name_or_path: "./models/colstella2.5_base"
    torch_dtype:  !ext torch.float
    attn_implementation: "sdpa"
    unpad_inputs: false
    use_memory_efficient_attention: true
    vision_attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_mixed_multiL_train_set
  eval_dataset_loader: !import ../data/test_data.yaml

  # max_length: 50
  run_eval: true
  loss_func:
    (): colpali_engine.loss.late_interaction_losses.ColbertPairwiseCELoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 1
    per_device_train_batch_size: 256
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    gradient_accumulation_steps: 2
    per_device_eval_batch_size: 128
    eval_strategy: "steps"
    dataloader_num_workers: 4
    bf16: true
    save_steps: 50
    logging_steps: 1
    eval_steps: 100
    warmup_steps: 50
    learning_rate: 5e-4
    save_total_limit: null
    # resume_from_checkpoint: true
    # optim: "paged_adamw_8bit"
    # wandb logging
    # wandb_project: "small_colstella"
    run_name: "colstella2.5_lora128_bsz256x2_lr5e-4"
    report_to: "wandb"
    deepspeed: "/root/colpali/deep_speed_config.json"


  peft_config:
    (): peft.LoraConfig
    r: 128
    lora_alpha: 128
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(new).*(down_proj|up_gate_proj|qkv_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'

